import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,within,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import {makeApartmentFavorite,validApartmentFavorites} from '../src/apartment-favorites.js';
import {readPreferences,savePreferences} from '../src/preferences.js';
const region={region_id:'dong_41465101',region_code:'41465',region_name:'경기도 용인시 수지구',label:'경기도 용인시 수지구 풍덕천동',dongs:['풍덕천동']};
const other={region_id:'dong_11110101',region_code:'11110',region_name:'서울특별시 종로구',label:'서울특별시 종로구 청운동',dongs:['청운동']};
const manifest={regions:[region,other],districts:{'41465':{file:'suji.json',months:['202609','202610']},'11110':{file:'seoul.json',months:['202609','202610']}},months:['202609','202610'],published_at:'2026-10-03T12:00:00Z',count:8};
const row=(id,overrides={})=>({id,region_code:'41465',dong:'풍덕천동',jibun:'1',apartment:'동일아파트',road_address:'',area_m2:85,price_man:100000,floor:10,cancelled:0,deal_date:'2026-09-28',deal_month:'202609',raw:{},...overrides});
const label=item=>item.apartment+' · '+item.region_name+' '+item.dong+' · 지번 '+(item.jibun||'미상');
const table=(item,mode='주간')=>screen.getByRole('region',{name:label(item)+' '+mode+' 거래 내역'});
const favorite=makeApartmentFavorite(row(1),region);
beforeEach(()=>{window.localStorage.clear();window.history.replaceState(null,'','/?tab=dashboard');});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
describe('Personal apartment watchlist',()=>{
  it('isolates same-name apartments by district and lot, loads shared districts once, and excludes cancellations from price statistics',async()=>{
    const second=makeApartmentFavorite(row(2,{jibun:'2'}),region),third=makeApartmentFavorite(row(3,{region_code:'11110',dong:'청운동'}),other);
    savePreferences('viewer',{apartments:[favorite,second,third]});
    const loader=vi.fn((_,code)=>Promise.resolve(code==='41465'?[row(1),row(2,{cancelled:1,price_man:900000,raw:{cdealDay:'2026-10-01'}}),row(3,{jibun:'2',price_man:120000}),row(4,{jibun:'3',price_man:990000})]:[row(1,{region_code:code,dong:'청운동',price_man:50000})]));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:label(third)+' 주간 거래 내역'});
    expect(loader).toHaveBeenCalledTimes(2);
    expect(within(table(favorite)).getAllByRole('row')).toHaveLength(3);
    expect(within(table(second)).getAllByRole('row')).toHaveLength(2);
    expect(within(table(third)).getByText('5.00억 원')).toBeTruthy();
    const stats=screen.getByLabelText(label(favorite)+' 주간 통계');
    expect(within(stats).getByText('유효 거래').parentElement.textContent).toBe('유효 거래1건');
    expect(within(stats).getByText('최고 거래금액').parentElement.textContent).toBe('최고 거래금액10.00억 원');
    expect(within(stats).getByText('최근 거래가격').parentElement.textContent).toBe('최근 거래가격10.00억 원');
    expect(within(table(favorite)).getByText('해제일 2026-10-01')).toBeTruthy();
    expect(within(table(second)).queryByText('99.00억 원')).toBeNull();
    const user=userEvent.setup();await user.click(screen.getByRole('checkbox',{name:'해제 거래 포함'}));
    expect(within(table(favorite)).getAllByRole('row')).toHaveLength(2);
  });
  it('paginates and resets filters, restores favorites and period after reopening, and persists removals',async()=>{
    savePreferences('viewer',{apartments:[favorite]});
    const loader=vi.fn(()=>Promise.resolve(Array.from({length:52},(_,index)=>row(index+1,{area_m2:index===0?60:85,price_man:index===0?60000:100000}))));
    const user=userEvent.setup(),first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:label(favorite)+' 주간 거래 내역'});
    await user.click(screen.getByRole('button',{name:label(favorite)+' 다음 거래 페이지'}));
    expect(within(table(favorite)).getAllByRole('row')).toHaveLength(3);
    await user.click(screen.getByRole('button',{name:'10평대',exact:true}));
    expect(within(table(favorite)).getAllByRole('row')).toHaveLength(2);
    expect(screen.getByRole('button',{name:label(favorite)+' 이전 거래 페이지'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'최근 30일',exact:true}));
    expect(screen.getByLabelText('조회 시작일').value).toBe('2026-09-04');
    first.unmount();window.history.replaceState(null,'','/');
    const second=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:label(favorite)+' 기간별 거래 내역'});
    expect(screen.getByLabelText('조회 시작일').value).toBe('2026-09-04');
    expect(screen.getByRole('button',{name:'10평대',exact:true}).getAttribute('aria-pressed')).toBe('true');
    await user.click(screen.getByRole('button',{name:'면적 필터 초기화'}));
    expect(within(table(favorite,'기간별')).getAllByRole('row')).toHaveLength(51);
    await user.click(screen.getByRole('button',{name:label(favorite)+' 즐겨찾기 해제'}));
    expect(screen.getByText('즐겨찾기한 아파트가 없습니다.')).toBeTruthy();
    expect(readPreferences('viewer').apartments).toEqual([]);
    second.unmount();render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByText('즐겨찾기한 아파트가 없습니다.');
  });
  it('adds favorites from weekly rows without duplicates, restores them, and preserves empty or failed favorites',async()=>{
    const user=userEvent.setup();window.history.replaceState(null,'',`/?tab=weekly&dong=${region.region_id}`);
    let fail=false;
    const loader=vi.fn(()=>fail?Promise.reject(new Error('offline')):Promise.resolve([row(1),row(2)]));
    const first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    const trades=await screen.findByRole('region',{name:region.label+' 주간 거래 내역'});
    await user.click(within(trades).getAllByRole('button',{name:/즐겨찾기 추가/})[0]);
    expect(within(trades).getAllByRole('button',{name:/즐겨찾기 해제/})).toHaveLength(2);
    expect(readPreferences('viewer').apartments).toHaveLength(1);
    first.unmount();fail=true;window.history.replaceState(null,'','/?tab=dashboard');
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('alert');
    expect(readPreferences('viewer').apartments).toHaveLength(1);
    fail=false;await user.click(screen.getByRole('button',{name:'다시 불러오기',exact:true}));
    await screen.findByRole('region',{name:label(favorite)+' 주간 거래 내역'});
    await user.click(screen.getByRole('button',{name:'이전 주',exact:true}));
    expect(screen.getByText('이 주에 조회되는 거래가 없습니다.')).toBeTruthy();
    expect(readPreferences('viewer').apartments).toHaveLength(1);
  });
  it('rejects damaged or duplicate favorites without requesting arbitrary districts',async()=>{
    savePreferences('viewer',{apartments:[favorite]});
    for(let index=0;index<100;index++)savePreferences('apartment:'+index,{area:'85'});
    expect(readPreferences('viewer').apartments).toEqual([favorite]);
    expect(validApartmentFavorites([favorite,{...favorite}])).toBe(false);
    expect(validApartmentFavorites([{...favorite,id:'forged'}])).toBe(false);
    savePreferences('viewer',{apartments:[{...favorite,region_code:'not-a-district'}]});
    const loader=vi.fn();render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByText('즐겨찾기한 아파트가 없습니다.');expect(loader).not.toHaveBeenCalled();
  });
});
