import React from 'react';
import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import {makeApartmentFavorite} from '../src/apartment-favorites.js';
import {readPreferences,savePreferences} from '../src/preferences.js';
import {restoreTransactionFilters,areaMatches} from '../src/transaction-filters.js';
import {PYEONG_M2} from '../src/domain.mjs';
const region={region_id:'dong_41465101',label:'경기도 용인시 수지구 풍덕천동',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:['풍덕천동']};
const manifest={regions:[region],districts:{'41465':{file:'test.json',months:['202609','202610']}},months:['202609','202610'],published_at:'2026-10-03T12:00:00Z',count:7};
const row=(id,deal_date,area_m2,price_man,overrides={})=>({id,region_code:'41465',dong:'풍덕천동',jibun:'1',apartment:'공통단지',deal_date,deal_month:deal_date.replaceAll('-','').slice(0,6),area_m2,price_man,cancelled:0,floor:10,raw:{},...overrides});
const rows=[row(1,'2026-09-27',60,30000),row(2,'2026-09-28',60,60000),row(3,'2026-10-02',85,80000),row(4,'2026-10-02',120,120000),row(5,'2026-10-03',60,40000),row(6,'2026-09-29',60,990000,{cancelled:1}),row(7,'2026-09-29',60,800000,{jibun:'2'})];
const favorite=makeApartmentFavorite(rows[0],region);
beforeEach(()=>{window.localStorage.clear();window.history.replaceState(null,'','/');});
afterEach(cleanup);
describe('Shared transaction filters',()=>{
  it('applies the same exact dates and nonadjacent area bands to all tabs, statistics and charts, then restores them',async()=>{
    const user=userEvent.setup();savePreferences('viewer',{apartments:[favorite]});
    window.history.replaceState(null,'',`/?tab=weekly&dong=${region.region_id}&period=custom&from=2026-09-28&to=2026-10-02`);
    const first=render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    await screen.findByRole('region',{name:region.label+' 기간별 거래 내역'});
    fireEvent.change(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}),{target:{value:'60'}});
    fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'120'}});
    await user.click(screen.getByRole('button',{name:'10평대',exact:true}));
    await user.click(screen.getByRole('button',{name:'30평대',exact:true}));
    let table=screen.getByRole('region',{name:region.label+' 기간별 거래 내역'});
    expect(within(table).getAllByRole('row')).toHaveLength(5);
    expect(within(table).queryByText('8.00억 원')).toBeNull();
    await user.click(screen.getByRole('button',{name:'대시보드',exact:true}));
    table=await screen.findByRole('region',{name:/공통단지.*기간별 거래 내역/});
    expect(within(table).getAllByRole('row')).toHaveLength(4);
    expect(screen.getByLabelText('조회 시작일').value).toBe('2026-09-28');
    expect(screen.getByLabelText('조회 종료일').value).toBe('2026-10-02');
    expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value).toBe('120');
    const stats=screen.getByLabelText(/공통단지.*기간별 통계/);
    expect(within(stats).getByText('최저 거래금액').parentElement.textContent).toBe('최저 거래금액6.00억 원');
    expect(within(stats).getByText('최고 거래금액').parentElement.textContent).toBe('최고 거래금액12.00억 원');
    await user.click(screen.getByRole('button',{name:/공통단지.*아파트 상세 보기/}));
    table=await screen.findByRole('region',{name:'선택 아파트 실거래 내역'});
    expect(within(table).getAllByRole('row')).toHaveLength(3);
    expect(screen.getAllByRole('group',{name:'공통 조회 필터'})).toHaveLength(1);
    expect(screen.queryByRole('combobox',{name:'시작 계약월'})).toBeNull();
    expect(screen.queryByRole('combobox',{name:'단지 전용면적'})).toBeNull();
    const detailStats=screen.getByLabelText('선택 아파트 통계');
    expect(within(detailStats).getByText('조회 거래건수').parentElement.querySelector('strong').textContent).toBe('2건');
    await user.click(screen.getByText('단지 월별 수치 보기'));
    expect(screen.getByRole('cell',{name:'2026.09'}).closest('tr').textContent).toBe('2026.091건6.00억 원6.00억 원');
    expect(screen.getByRole('cell',{name:'2026.10'}).closest('tr').textContent).toBe('2026.101건12.00억 원12.00억 원');
    fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'100'}});
    expect(within(screen.getByRole('region',{name:'선택 아파트 실거래 내역'})).getAllByRole('row')).toHaveLength(2);
    expect(screen.getByRole('cell',{name:'2026.10'}).closest('tr').textContent).toBe('2026.100건—억 원—억 원');
    await user.click(screen.getByRole('button',{name:'평 (전용)',exact:true}));
    expect(readPreferences('transactionFilters').value).toMatchObject({minArea:60,maxArea:100,areaBands:[10,30],areaUnit:'pyeong'});
    first.unmount();window.history.replaceState(null,'','/');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    await screen.findByRole('heading',{name:'공통단지'});
    expect(screen.getByLabelText('조회 종료일').value).toBe('2026-10-02');
    expect(screen.getByRole('button',{name:'30평대',exact:true}).getAttribute('aria-pressed')).toBe('true');
    await user.click(screen.getByRole('button',{name:'동별 주간 실거래가',exact:true}));
    await screen.findByRole('region',{name:region.label+' 기간별 거래 내역'});
    expect(Number(screen.getByRole('spinbutton',{name:'최대 전용면적 (평)'}).value)).toBeCloseTo(100/PYEONG_M2,4);
    expect(new URLSearchParams(location.search).get('maxArea')).toBe('100');
    expect(new URLSearchParams(location.search).get('bands')).toBe('10,30');
  });
  it('migrates old per-tab settings and month links, while an explicit shared filter overrides cached limits',()=>{
    savePreferences('explorer',{tab:'dashboard'});
    savePreferences('favoriteDashboard',{day:'2026-09-28',period:{mode:'custom',month:'2026-09',start:'2026-09-01',end:'2026-10-02'},minArea:60,maxArea:85,areaBands:[20]});
    const migrated=restoreTransactionFilters(manifest);
    expect(migrated).toMatchObject({minArea:60,maxArea:85,areaBands:[20],period:{mode:'custom',start:'2026-09-01',end:'2026-10-02'}});
    savePreferences('transactionFilters',{value:migrated});
    const shared=restoreTransactionFilters(manifest,new URLSearchParams('period=month&month=2026-09&minArea=&maxArea=&bands=10,30&unit=pyeong'));
    expect(shared).toMatchObject({minArea:'',maxArea:'',areaBands:[10,30],areaUnit:'pyeong',period:{mode:'month',month:'2026-09'}});
    const legacy=restoreTransactionFilters(manifest,new URLSearchParams('tab=apartments&start=202609&end=202610'));
    expect(legacy.period).toMatchObject({mode:'custom',start:'2026-09-01',end:'2026-10-03'});
    for(const pyeong of [10,19.9999,30,39.9999])expect(areaMatches({area_m2:pyeong*PYEONG_M2},shared)).toBe(true);
    for(const pyeong of [9.9999,20,29.9999,40])expect(areaMatches({area_m2:pyeong*PYEONG_M2},shared)).toBe(false);
  });
  it('shows invalid periods in all tabs and retains the selected apartment when no trade matches',async()=>{
    const user=userEvent.setup();window.history.replaceState(null,'','/?tab=apartments&region=area_41465&period=custom&from=2026-09-28&to=2026-10-02');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    await screen.findByRole('combobox',{name:'조회 아파트'});
    await user.selectOptions(screen.getByRole('combobox',{name:'조회 아파트'}),favorite.key);
    fireEvent.change(screen.getByLabelText('조회 종료일'),{target:{value:'2026-09-27'}});
    expect(screen.getByRole('alert').textContent).toContain('시작일은 종료일보다');
    expect(screen.getByRole('heading',{name:'공통단지'})).toBeTruthy();
    expect(screen.getByText('조회 조건에 맞는 유효 거래가 없습니다.')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'대시보드',exact:true}));
    await screen.findByRole('heading',{name:'즐겨찾기 아파트 실거래가'});
    expect(screen.getByRole('alert').textContent).toContain('시작일은 종료일보다');
    expect(screen.getByLabelText('조회 종료일').value).toBe('2026-09-27');
  });
});
