import React from 'react';
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest';
import {cleanup, fireEvent, render, screen, waitFor, within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import RawTable from '../admin/RawTable.jsx';
import {savePreferences} from '../src/preferences.js';
const region={region_id:'suji',label:'용인 수지구',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:[]};
const rows=Array.from({length:115},(_,i)=>({id:i+1,region_code:'41465',deal_month:'202601',deal_date:'2026-01-05',apartment:i===0?'첫 아파트':'두번째',dong:'풍덕천동',jibun:'1',road_address:'경기도 용인시 수지구 풍덕천로 12',price_man:100000,area_m2:85,cancelled:0,raw:{aptNm:i===0?'첫 아파트':'두번째',umdNm:'풍덕천동',dealAmount:i===0?'100,000':'50,000',floor:'4',cdealType:''}}));
const manifest={regions:[region,{region_id:'dong_11110101',label:'서울특별시 종로구 청운동',region_name:'서울특별시 종로구',region_code:'11110',dongs:['청운동']}],districts:{'41465':{file:'fake.json',count:115,months:['202601']}},months:['202601'],published_at:'2026-10-02T00:00:00+00:00',count:115,boundary_catalog_date:'2023-07-29'};
beforeEach(()=>{window.localStorage.clear();window.history.replaceState(null,'','/?region=area_41465&tab=apartments');});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('React transaction explorer',()=>{
  it('adds a personal apartment favorite through search while selecting multiple trades in the unified tab',async()=>{
    const user=userEvent.setup();window.history.replaceState(null,'','/?region=area_41465&tab=apartments&period=month&month=2026-01');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const search=await screen.findByRole('group',{name:'검색 아파트 선택'});
    await user.click(within(search).getByRole('button',{name:/첫 아파트.*즐겨찾기 추가/}));
    await user.click(within(search).getByRole('checkbox',{name:/첫 아파트/}));
    const table=await screen.findByRole('region',{name:/첫 아파트.*기간별 거래 내역/});expect(within(table).getAllByRole('row')).toHaveLength(2);expect(within(table).queryByText('두번째')).toBeNull();
    expect(within(screen.getByRole('group',{name:'즐겨찾기 아파트 선택'})).getByRole('checkbox').checked).toBe(true);expect(screen.getByRole('button',{name:'대시보드',exact:true})).toBeTruthy();
  });
  it('loads the apartment tab directly from its public URL without dashboard detail',async()=>{
    window.history.replaceState(null,'','/?region=area_41465&tab=apartments');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const apartments=screen.getByRole('tabpanel',{name:'아파트별 실거래가'});
    await within(apartments).findByRole('searchbox',{name:'아파트 검색'});
    expect((await within(apartments).findByRole('group',{name:'검색 아파트 선택'})).querySelectorAll('input:checked')).toHaveLength(0);
    expect(screen.queryByText('유효 거래',{selector:'.metric-label'})).toBeNull();
    expect(screen.queryByRole('button',{name:'원천 데이터',exact:true})).toBeNull();
  });
  it('an old raw-data URL resolves to the overview dashboard without exposing a raw table',async()=>{
    window.history.replaceState(null,'','/?region=area_41465&tab=raw');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    await screen.findByText('즐겨찾기를 추가해 대시보드를 채워보세요.');
    expect(screen.getByRole('tabpanel',{name:'대시보드'})).toBeTruthy();
    expect(screen.queryByText('신고 자료 그대로')).toBeNull();
    expect(screen.queryByRole('button',{name:'CSV 다운로드'})).toBeNull();
    expect(window.location.search).toContain('tab=dashboard');
  });
  it('keeps period and area controls inside unified apartment transactions and removes them from the about tab',async()=>{
    const user=userEvent.setup();render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const dashboard=screen.getByRole('tabpanel',{name:'아파트별 실거래가'});
    await within(dashboard).findByLabelText('조회 주 기준 날짜');
    expect(within(dashboard).getByRole('spinbutton',{name:'최소 전용면적 (㎡)'})).toBeTruthy();
    expect(within(dashboard).getByRole('combobox',{name:'조회 지역'})).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'데이터 안내'}));
    expect(screen.queryByLabelText('조회 주 기준 날짜')).toBeNull();
    expect(screen.queryByRole('button',{name:'원천 데이터'})).toBeNull();
    expect(screen.queryByRole('button',{name:'CSV 다운로드'})).toBeNull();
  });
  it('adds a filterable exclusive-pyeong column while retaining source square metres in CSV',async()=>{
    const user=userEvent.setup(),blobs=[];
    Object.defineProperty(URL,'createObjectURL',{value:vi.fn(blob=>{blobs.push(blob);return 'blob:test';}),configurable:true});
    Object.defineProperty(URL,'revokeObjectURL',{value:vi.fn(),configurable:true});
    vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
    const sample=[60,85].map((area,i)=>({...rows[i],area_m2:area,raw:{...rows[i].raw,excluUseAr:String(area)}}));
    render(<RawTable rows={sample} region={region} start="202601" end="202601"/>);
    await user.click(screen.getByRole('button',{name:'평 (전용)'}));
    expect(screen.getByText('25.71')).toBeTruthy();expect(screen.getByText('85')).toBeTruthy();
    await user.click(screen.getByLabelText('전용면적(평 · 환산) 필터'));
    await user.selectOptions(screen.getByRole('combobox',{name:'__exclusivePyeong 필터 조건'}),'gte');
    await user.type(screen.getByRole('textbox',{name:'__exclusivePyeong 필터 값'}),'20');
    expect(screen.queryByText('첫 아파트')).toBeNull();
    await user.click(screen.getByRole('button',{name:'CSV 다운로드'}));
    const content=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsText(blobs[0]);});
    expect(content).toContain('전용면적(㎡)');expect(content).toContain('"85"');
    expect(content).not.toContain('환산');expect(content.split('\r\n')).toHaveLength(2);
    expect(sample[1].raw.excluUseAr).toBe('85');
  });
  it('starts with empty personal favorites and makes no district request',async()=>{
    window.history.replaceState(null,'','/');const loader=vi.fn(()=>Promise.resolve(rows));
    render(<App initialManifest={{...manifest,favorite_region_ids:[]}} districtLoader={loader}/>);
    await screen.findByText('즐겨찾기를 추가해 대시보드를 채워보세요.');
    expect(screen.queryByRole('combobox',{name:'조회 지역'})).toBeNull();
    expect(loader).not.toHaveBeenCalled();
    expect(window.location.search).not.toContain('region=');
  });
  it('shows saved dong favorites and opens only the chosen region without a preset',async()=>{
    window.history.replaceState(null,'','/?tab=apartments');
    const user=userEvent.setup();
    const favorite={region_id:'dong_41465101',label:'경기도 용인시 수지구 풍덕천동',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:['풍덕천동']};
    savePreferences('viewer',{regions:[favorite.region_id]});
    const loader=vi.fn(()=>Promise.resolve(rows));
    render(<App initialManifest={{...manifest,regions:[...manifest.regions,favorite],favorite_region_ids:['dong_11110101']}} districtLoader={loader}/>);
    await screen.findByRole('region',{name:'즐겨찾기 지역'});
    const section=screen.getByRole('region',{name:'즐겨찾기 지역'});
    await user.click(within(section).getByRole('button',{name:/풍덕천동/}));
    await screen.findByRole('group',{name:'검색 아파트 선택'});
    expect(loader).toHaveBeenCalledWith(expect.anything(),'41465');
    expect(window.location.search).toContain(favorite.region_id);
    await user.click(screen.getByRole('button',{name:'조회 선택 해제'}));
    expect(screen.getByText('아파트를 찾을 지역을 선택해 주세요.')).toBeTruthy();
    expect(window.location.search).not.toContain('region=');
  });
  it('filters by an individual column, resets pagination, and keeps raw strings',async()=>{
    const user=userEvent.setup();
    render(<RawTable rows={rows} region={region} start="202601" end="202601"/>);
    expect(screen.getByText('100,000')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'다음 페이지'}));
    expect(screen.queryByText('첫 아파트')).toBeNull();
    await user.click(screen.getByLabelText('아파트명 필터'));
    await user.type(screen.getByRole('textbox',{name:'aptNm 필터 값'}),'첫');
    expect(screen.getByText('첫 아파트')).toBeTruthy();
    expect(screen.getByRole('button',{name:'다음 페이지'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'필터 초기화'}));
    expect(screen.getByRole('button',{name:'다음 페이지'}).disabled).toBe(false);
  });
  it('numeric errors are visible and CSV exports all filtered rows rather than one page',async()=>{
    const user=userEvent.setup();
    const blobs=[];
    const create=vi.fn(blob=>{blobs.push(blob);return 'blob:test';});
    Object.defineProperty(URL,'createObjectURL',{value:create,configurable:true});
    Object.defineProperty(URL,'revokeObjectURL',{value:vi.fn(),configurable:true});
    vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
    render(<RawTable rows={rows} region={region} start="202601" end="202601"/>);
    await user.click(screen.getByLabelText('거래금액(만원) 필터'));
    await user.selectOptions(screen.getByRole('combobox',{name:'dealAmount 필터 조건'}),'gte');
    await user.type(screen.getByRole('textbox',{name:'dealAmount 필터 값'}),'bad');
    expect(screen.getByRole('alert').textContent).toContain('숫자');
    expect(screen.getByRole('button',{name:'CSV 다운로드'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'필터 초기화'}));
    await user.click(screen.getByRole('button',{name:'CSV 다운로드'}));
    const content=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsText(blobs[0]);});
    expect(content.split('\r\n').length).toBe(116);
  });
  it('allows city/district/dong navigation to an uncollected scope and exposes no collector',async()=>{
    const user=userEvent.setup();
    const loader=vi.fn((_,code)=>Promise.resolve(code==='41465'?rows:[]));
    window.history.replaceState(null,'','/?region=area_41465&tab=apartments');
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('group',{name:'검색 아파트 선택'});
    await user.selectOptions(screen.getByRole('combobox',{name:'시도'}),'서울특별시');
    await user.selectOptions(screen.getByRole('combobox',{name:'조회 지역'}),'dong_11110101');
    await screen.findByText('아직 수집된 자료가 없는 지역입니다. 즐겨찾기한 아파트는 위에서 선택할 수 있습니다.');
    expect(window.location.search).toContain('dong_11110101');
    expect(screen.queryByRole('button',{name:'선택 지역 수집'})).toBeNull();
    await user.click(screen.getByRole('button',{name:'데이터 안내'}));
    expect(screen.getByRole('link',{name:'웹 수집 관리자'}).getAttribute('href')).toBe('/admin.html');
    expect(screen.getByRole('link',{name:'공개 SQLite 다운로드'}).getAttribute('href')).toBe('/data/public.sqlite3');
  });
  it('uses the manifest SQLite archive link and explains decompression for large datasets',()=>{
    window.history.replaceState(null,'','/?tab=about');
    render(<App initialManifest={{...manifest,database:{file:'public.sqlite3.gz',format:'sqlite3+gzip'}}}/>);
    expect(screen.getByRole('link',{name:'공개 SQLite 다운로드 (.gz)'}).getAttribute('href')).toBe('/data/public.sqlite3.gz');
    expect(screen.getByText(/다운로드 후 gzip 압축을 풀면/)).toBeTruthy();
  });
  it('does not display a stale district when a slow previous request finishes',async()=>{
    const user=userEvent.setup();
    let resolveOld;
    const loader=vi.fn((_,code)=>code==='41465'?new Promise(resolve=>{resolveOld=resolve;}):Promise.resolve([]));
    window.history.replaceState(null,'','/?region=area_41465&tab=apartments');
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await user.selectOptions(screen.getByRole('combobox',{name:'조회 지역'}),'dong_11110101');
    await screen.findByText('아직 수집된 자료가 없는 지역입니다. 즐겨찾기한 아파트는 위에서 선택할 수 있습니다.');
    resolveOld(rows);
    await waitFor(()=>expect(screen.queryByText('첫 아파트')).toBeNull());
  });
});
