import React from 'react';
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest';
import {cleanup, render, screen, waitFor, within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import RawTable from '../admin/RawTable.jsx';
import Dashboard from '../src/Dashboard.jsx';
const region={region_id:'suji',label:'용인 수지구',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:[]};
const rows=Array.from({length:115},(_,i)=>({id:i+1,region_code:'41465',deal_month:'202601',deal_date:'2026-01-05',apartment:i===0?'첫 아파트':'두번째',dong:'풍덕천동',jibun:'1',road_address:'경기도 용인시 수지구 풍덕천로 12',price_man:100000,area_m2:85,cancelled:0,raw:{aptNm:i===0?'첫 아파트':'두번째',umdNm:'풍덕천동',dealAmount:i===0?'100,000':'50,000',floor:'4',cdealType:''}}));
const manifest={regions:[region,{region_id:'dong_11110101',label:'서울특별시 종로구 청운동',region_name:'서울특별시 종로구',region_code:'11110',dongs:['청운동']}],districts:{'41465':{file:'fake.json',count:115,months:['202601']}},months:['202601'],published_at:'2026-10-02T00:00:00+00:00',count:115,boundary_catalog_date:'2023-07-29'};
beforeEach(()=>{window.localStorage.clear();window.history.replaceState(null,'','/?region=area_41465&tab=dashboard');});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('React transaction explorer',()=>{
  it('keeps apartment detail in its own tab and opens summary links there with the same region and period',async()=>{
    const user=userEvent.setup();
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const dashboard=screen.getByRole('tabpanel',{name:'대시보드'});
    await within(dashboard).findByText('유효 거래',{selector:'.metric-label'});
    expect(within(dashboard).queryByRole('searchbox',{name:'아파트 검색'})).toBeNull();
    expect(within(dashboard).queryByRole('region',{name:'선택 아파트 실거래 내역'})).toBeNull();
    await user.click(within(dashboard).getByRole('button',{name:'첫 아파트 경기도 용인시 수지구 풍덕천로 12 실거래 보기'}));
    const apartments=screen.getByRole('tabpanel',{name:'아파트별 실거래가'});
    await within(apartments).findByRole('heading',{name:'첫 아파트'});
    expect(within(apartments).getByText('경기도 용인시 수지구 풍덕천로 12',{selector:'.apartment-heading p'})).toBeTruthy();
    expect(within(apartments).getByRole('combobox',{name:'조회 지역'}).value).toBe('area_41465');
    expect(within(apartments).getByRole('combobox',{name:'시작 계약월'}).value).toBe('202601');
    expect(within(apartments).getByRole('region',{name:'선택 아파트 실거래 내역'})).toBeTruthy();
    expect(within(apartments).queryByText('거래의 흐름')).toBeNull();
    expect(window.location.search).toContain('tab=apartments');
    await user.click(screen.getByRole('button',{name:'대시보드',exact:true}));
    await screen.findByText('유효 거래',{selector:'.metric-label'});
    expect(screen.queryByRole('searchbox',{name:'아파트 검색'})).toBeNull();
    await user.click(screen.getByRole('button',{name:'아파트별 실거래가',exact:true}));
    await screen.findByRole('heading',{name:'첫 아파트'});
  });
  it('loads the apartment tab directly from its public URL without dashboard detail',async()=>{
    window.history.replaceState(null,'','/?region=area_41465&tab=apartments');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const apartments=screen.getByRole('tabpanel',{name:'아파트별 실거래가'});
    await within(apartments).findByRole('searchbox',{name:'아파트 검색'});
    expect(within(apartments).getByRole('combobox',{name:'조회 아파트'}).value).toBe('');
    expect(screen.queryByText('유효 거래',{selector:'.metric-label'})).toBeNull();
    expect(screen.queryByRole('button',{name:'원천 데이터',exact:true})).toBeNull();
  });
  it('an old raw-data URL resolves to the public dashboard without exposing a table',async()=>{
    window.history.replaceState(null,'','/?region=area_41465&tab=raw');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    await screen.findByText('유효 거래',{selector:'.metric-label'});
    expect(screen.getByRole('tabpanel',{name:'대시보드'})).toBeTruthy();
    expect(screen.queryByText('신고 자료 그대로')).toBeNull();
    expect(screen.queryByRole('button',{name:'CSV 다운로드'})).toBeNull();
    expect(window.location.search).toContain('tab=dashboard');
  });
  it('keeps dashboard controls inside its tab and removes the public raw-data view',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'','/?region=area_41465&tab=dashboard');
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(rows)}/>);
    const dashboard=screen.getByRole('tabpanel',{name:'대시보드'});
    expect(within(dashboard).getByRole('combobox',{name:'조회 지역'}).value).toBe('area_41465');
    expect(within(dashboard).getByRole('combobox',{name:'시작 계약월'})).toBeTruthy();
    await within(dashboard).findByText('유효 거래',{selector:'.metric-label'});
    await user.click(screen.getByRole('button',{name:'데이터 안내'}));
    expect(screen.queryByRole('combobox',{name:'조회 지역'})).toBeNull();
    expect(within(screen.getByRole('tabpanel',{name:'데이터 안내'})).getByText('공개 데이터')).toBeTruthy();
    expect(screen.queryByRole('button',{name:'원천 데이터'})).toBeNull();
    expect(screen.queryByRole('button',{name:'CSV 다운로드'})).toBeNull();
  });
  it('converts dashboard filters, price units, area bands and apartment areas without changing boundary trades',async()=>{
    const user=userEvent.setup();
    const sample=[60,85,85.001,102].map((area,i)=>({...rows[0],id:i,area_m2:area}));
    render(<Dashboard rows={sample} region={region} manifest={manifest} favorites={[]} start="202601" end="202601" districtLoader={()=>Promise.resolve([])}/>);
    const minimum=screen.getByRole('spinbutton',{name:/최소 전용면적/});
    const maximum=screen.getByRole('spinbutton',{name:/최대 전용면적/});
    await user.clear(minimum);await user.type(minimum,'60');
    await user.clear(maximum);await user.type(maximum,'85');
    const count=()=>screen.getByText('유효 거래',{selector:'.metric-label'}).closest('section').querySelector('.metric-value').textContent;
    expect(count()).toBe('2건');
    await user.click(screen.getByRole('button',{name:'평 (전용)'}));
    expect(Number(minimum.value)).toBeCloseTo(18.15,2);
    expect(Number(maximum.value)).toBeCloseTo(25.71,2);
    expect(count()).toBe('2건');
    expect(screen.getByText('전용평당 중앙값',{selector:'.metric-label'})).toBeTruthy();
    expect(screen.getByText('평균 전용면적 (평)')).toBeTruthy();
    expect(screen.getByText('21.93평')).toBeTruthy();
    expect(screen.getByText('18.15–25.71평')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'㎡',exact:true}));
    expect(minimum.value).toBe('60');expect(maximum.value).toBe('85');
    expect(count()).toBe('2건');
    expect(screen.getByText('전용㎡당 중앙값',{selector:'.metric-label'})).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'평 (전용)'}));
    await user.clear(maximum);await user.type(maximum,'20');
    expect(count()).toBe('1건');
  });
  it('adds a filterable exclusive-pyeong column while retaining source square metres in CSV',async()=>{
    const user=userEvent.setup(),blobs=[];
    Object.defineProperty(URL,'createObjectURL',{value:vi.fn(blob=>{blobs.push(blob);return 'blob:test';}),configurable:true});
    Object.defineProperty(URL,'revokeObjectURL',{value:vi.fn(),configurable:true});
    vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
    const sample=[60,85].map((area,i)=>({...rows[i],area_m2:area,raw:{...rows[i].raw,excluUseAr:String(area)}}));
    render(<RawTable rows={sample} region={region} start="202601" end="202601"/>);
    await user.click(screen.getByRole('button',{name:'평 (전용)'}));
    expect(screen.getByText('25.71')).toBeTruthy();expect(screen.getByText('85')).toBeTruthy();
    await user.click(screen.getByLabelText('전용면적(평 · 환산) 필터'));
    await user.selectOptions(screen.getByRole('combobox',{name:'__exclusivePyeong 필터 조건'}),'gte');
    await user.type(screen.getByRole('textbox',{name:'__exclusivePyeong 필터 값'}),'20');
    expect(screen.queryByText('첫 아파트')).toBeNull();
    await user.click(screen.getByRole('button',{name:'CSV 다운로드'}));
    const content=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsText(blobs[0]);});
    expect(content).toContain('전용면적(㎡)');expect(content).toContain('"85"');
    expect(content).not.toContain('환산');expect(content.split('\r\n')).toHaveLength(2);
    expect(sample[1].raw.excluUseAr).toBe('85');
  });
  it('starts with no region and no data request when favorites are empty',async()=>{
    window.history.replaceState(null,'','/');
    const loader=vi.fn(()=>Promise.resolve(rows));
    render(<App initialManifest={{...manifest,favorite_region_ids:[]}} districtLoader={loader}/>);
    expect(screen.getByText('등록된 즐겨찾기 지역이 없습니다.')).toBeTruthy();
    expect(screen.getByText('조회할 지역을 선택해 주세요.')).toBeTruthy();
    expect(screen.getByRole('combobox',{name:'조회 지역'}).value).toBe('');
    expect(loader).not.toHaveBeenCalled();
    expect(screen.queryByRole('button',{name:'용인 수지구'})).toBeNull();
    expect(screen.queryByRole('option',{name:'용인 수지구'})).toBeNull();
    expect(window.location.search).not.toContain('region=');
  });
  it('shows saved dong favorites and opens only the chosen region without a preset',async()=>{
    window.history.replaceState(null,'','/?tab=dashboard');
    const user=userEvent.setup();
    const favorite={region_id:'dong_41465101',label:'경기도 용인시 수지구 풍덕천동',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:['풍덕천동']};
    const loader=vi.fn(()=>Promise.resolve(rows));
    render(<App initialManifest={{...manifest,regions:[...manifest.regions,favorite],favorite_region_ids:[favorite.region_id]}} districtLoader={loader}/>);
    expect(loader).not.toHaveBeenCalled();
    const section=screen.getByRole('region',{name:'즐겨찾기 지역'});
    await user.click(within(section).getByRole('button',{name:/풍덕천동/}));
    await screen.findByText('첫 아파트');
    expect(loader).toHaveBeenCalledWith(expect.anything(),'41465');
    expect(window.location.search).toContain(favorite.region_id);
    await user.click(screen.getByRole('button',{name:'조회 선택 해제'}));
    expect(screen.getByText('조회할 지역을 선택해 주세요.')).toBeTruthy();
    expect(window.location.search).not.toContain('region=');
  });
  it('renders real charts and excludes cancelled transactions from dashboard statistics',async()=>{
    vi.stubGlobal('ResizeObserver',class {
      constructor(callback){this.callback=callback;}
      observe(){this.callback([{contentRect:{width:800,height:300}}]);}
      unobserve(){}
      disconnect(){}
    });
    vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockReturnValue({width:800,height:300,top:0,left:0,right:800,bottom:300,x:0,y:0,toJSON(){}});
    const sample=[rows[0],{...rows[1],cancelled:1,price_man:900000}];
    const favorites=[{...region,region_id:'dong_41465101',label:'즐겨찾기 풍덕천동',dongs:['풍덕천동']},
      {...region,region_id:'dong_41465102',label:'즐겨찾기 죽전동',dongs:['죽전동']}];
    const loader=vi.fn(()=>Promise.resolve(sample));
    render(<Dashboard rows={sample} region={region} manifest={manifest} favorites={favorites} start="202601" end="202601" districtLoader={loader}/>);
    await screen.findByText('1건의 해제 거래 제외');
    const metric=screen.getByText('유효 거래',{selector:'.metric-label'}).closest('section');
    expect(metric.querySelector('.metric-value').textContent).toBe('1건');
    expect(screen.getByText('거래금액 중앙값').closest('section').querySelector('.metric-value').textContent).toBe('10.00억 원');
    await waitFor(()=>expect(document.querySelectorAll('.recharts-surface').length).toBeGreaterThanOrEqual(3));
    await waitFor(()=>expect(screen.getByText('즐겨찾기 풍덕천동').closest('div').querySelector('p').textContent).toContain('1건'));
    expect(screen.getByText('즐겨찾기 죽전동').closest('div').querySelector('p').textContent).toContain('0건');
    expect(loader).toHaveBeenCalledTimes(1);
    expect(loader).toHaveBeenCalledWith(manifest,'41465');
  });
  it('filters by an individual column, resets pagination, and keeps raw strings',async()=>{
    const user=userEvent.setup();
    render(<RawTable rows={rows} region={region} start="202601" end="202601"/>);
    expect(screen.getByText('100,000')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'다음 페이지'}));
    expect(screen.queryByText('첫 아파트')).toBeNull();
    await user.click(screen.getByLabelText('아파트명 필터'));
    await user.type(screen.getByRole('textbox',{name:'aptNm 필터 값'}),'첫');
    expect(screen.getByText('첫 아파트')).toBeTruthy();
    expect(screen.getByRole('button',{name:'다음 페이지'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'필터 초기화'}));
    expect(screen.getByRole('button',{name:'다음 페이지'}).disabled).toBe(false);
  });
  it('numeric errors are visible and CSV exports all filtered rows rather than one page',async()=>{
    const user=userEvent.setup();
    const blobs=[];
    const create=vi.fn(blob=>{blobs.push(blob);return 'blob:test';});
    Object.defineProperty(URL,'createObjectURL',{value:create,configurable:true});
    Object.defineProperty(URL,'revokeObjectURL',{value:vi.fn(),configurable:true});
    vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
    render(<RawTable rows={rows} region={region} start="202601" end="202601"/>);
    await user.click(screen.getByLabelText('거래금액(만원) 필터'));
    await user.selectOptions(screen.getByRole('combobox',{name:'dealAmount 필터 조건'}),'gte');
    await user.type(screen.getByRole('textbox',{name:'dealAmount 필터 값'}),'bad');
    expect(screen.getByRole('alert').textContent).toContain('숫자');
    expect(screen.getByRole('button',{name:'CSV 다운로드'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'필터 초기화'}));
    await user.click(screen.getByRole('button',{name:'CSV 다운로드'}));
    const content=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsText(blobs[0]);});
    expect(content.split('\r\n').length).toBe(116);
  });
  it('allows city/district/dong navigation to an uncollected scope and exposes no collector',async()=>{
    const user=userEvent.setup();
    const loader=vi.fn((_,code)=>Promise.resolve(code==='41465'?rows:[]));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByText('첫 아파트');
    await user.selectOptions(screen.getByRole('combobox',{name:'시도'}),'서울특별시');
    await user.selectOptions(screen.getByRole('combobox',{name:'조회 지역'}),'dong_11110101');
    await screen.findByText('이 지역은 아직 수집된 자료가 없습니다.');
    expect(window.location.search).toContain('dong_11110101');
    expect(screen.queryByRole('button',{name:'선택 지역 수집'})).toBeNull();
    await user.click(screen.getByRole('button',{name:'데이터 안내'}));
    expect(screen.getByText('로컬 전용')).toBeTruthy();
    expect(screen.getByRole('link',{name:'공개 SQLite 다운로드'}).getAttribute('href')).toBe('/data/public.sqlite3');
  });
  it('uses the manifest SQLite archive link and explains decompression for large datasets',()=>{
    window.history.replaceState(null,'','/?tab=about');
    render(<App initialManifest={{...manifest,database:{file:'public.sqlite3.gz',format:'sqlite3+gzip'}}}/>);
    expect(screen.getByRole('link',{name:'공개 SQLite 다운로드 (.gz)'}).getAttribute('href')).toBe('/data/public.sqlite3.gz');
    expect(screen.getByText(/다운로드 후 gzip 압축을 풀면/)).toBeTruthy();
  });
  it('does not display a stale district when a slow previous request finishes',async()=>{
    const user=userEvent.setup();
    let resolveOld;
    const loader=vi.fn((_,code)=>code==='41465'?new Promise(resolve=>{resolveOld=resolve;}):Promise.resolve([]));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await user.selectOptions(screen.getByRole('combobox',{name:'조회 지역'}),'dong_11110101');
    await screen.findByText('이 지역은 아직 수집된 자료가 없습니다.');
    resolveOld(rows);
    await waitFor(()=>expect(screen.queryByText('첫 아파트')).toBeNull());
  });
});
