import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import {readPreferences,savePreferences} from '../src/preferences.js';
import {PYEONG_M2} from '../src/domain.mjs';

const a={region_id:'dong_41465101',label:'경기도 용인시 수지구 풍덕천동',region_name:'경기도 용인시 수지구',region_code:'41465',dongs:['풍덕천동']};
const b={region_id:'dong_11110101',label:'서울특별시 종로구 풍덕천동',region_name:'서울특별시 종로구',region_code:'11110',dongs:['풍덕천동']};
const c={...a,region_id:'dong_41465103',label:'경기도 용인시 수지구 동천동',dongs:['동천동']};
const uncollected={...a,region_id:'dong_41117101',label:'경기도 수원시 영통구 매탄동',region_name:'경기도 수원시 영통구',region_code:'41117',dongs:['매탄동']};
const manifest={regions:[a,b,c,uncollected],favorite_region_ids:[a.region_id],districts:{'41465':{file:'suji.json',months:['202609','202610']},'11110':{file:'seoul.json',months:['202610']}},months:['202609','202610'],published_at:'2026-10-03T12:00:00Z',count:8};
const row=(id,overrides={})=>({id,region_code:'41465',dong:'풍덕천동',apartment:'수지단지',jibun:'1',area_m2:85,price_man:100000,deal_month:'202609',deal_date:'2026-09-28',floor:10,cancelled:0,raw:{dealingGbn:'중개거래'},...overrides});
beforeEach(()=>{window.localStorage.clear();window.history.replaceState(null,'','/?tab=weekly');});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
describe('Dong weekly transaction tab',()=>{
  it('queries monthly and custom periods, validates dates, shares the period and restores it without losing dongs',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}`);
    const data=[row(1),row(2,{deal_month:'202610',deal_date:'2026-10-02'}),row(3,{deal_month:'202610',deal_date:'2026-10-04'})];
    const loader=vi.fn(()=>Promise.resolve(data));
    const first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    await user.click(screen.getByRole('button',{name:'월간',exact:true}));
    fireEvent.change(screen.getByLabelText('조회 월'),{target:{value:'2026-09'}});
    const table=()=>screen.getByRole('region',{name:`${a.label} 기간별 거래 내역`});
    expect(within(table()).getAllByRole('row')).toHaveLength(2);
    expect(new URLSearchParams(location.search).get('month')).toBe('2026-09');
    expect(screen.getByRole('button',{name:'이전 달'}).disabled).toBe(true);
    await user.click(screen.getByRole('button',{name:'직접 지정',exact:true}));
    fireEvent.change(screen.getByLabelText('조회 시작일'),{target:{value:'2026-09-28'}});
    fireEvent.change(screen.getByLabelText('조회 종료일'),{target:{value:'2026-10-02'}});
    expect(within(table()).getAllByRole('row')).toHaveLength(3);
    expect(new URLSearchParams(location.search).get('from')).toBe('2026-09-28');
    expect(loader).toHaveBeenCalledTimes(1);
    fireEvent.change(screen.getByLabelText('조회 시작일'),{target:{value:'2026-10-03'}});
    expect(screen.getByRole('alert').textContent).toContain('시작일은 종료일보다');
    expect(screen.queryByRole('region',{name:`${a.label} 기간별 거래 내역`})).toBeNull();
    fireEvent.change(screen.getByLabelText('조회 시작일'),{target:{value:'2026-09-28'}});
    first.unmount();window.history.replaceState(null,'','/');
    const second=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${a.label} 기간별 거래 내역`});
    expect(screen.getByLabelText('조회 종료일').value).toBe('2026-10-02');
    expect(readPreferences('explorer').weeklyIds).toEqual([a.region_id]);
    await user.click(screen.getByRole('button',{name:'최근 30일',exact:true}));
    expect(screen.getByLabelText('조회 시작일').value).toBe('2026-09-04');
    expect(screen.getByLabelText('조회 종료일').value).toBe('2026-10-03');
    second.unmount();window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&period=month&month=2026-09`);
    const third=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${a.label} 기간별 거래 내역`});
    expect(screen.getByLabelText('조회 월').value).toBe('2026-09');
    third.unmount();window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&week=2026-09-28`);
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(screen.getByRole('button',{name:'주간',exact:true}).getAttribute('aria-pressed')).toBe('true');
  });
  it('shows transaction rows without summary cards and still applies the area and week filters',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}`);
    const data=[6,8,10,10,12,15].map((price,index)=>row(index+1,{price_man:price*10000,apartment:`가격단지${index}`,area_m2:index===5?120:85}));
    data.push(row(99,{cancelled:1,price_man:990000,apartment:'해제최고가'}));
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve(data)}/>);
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    const table=()=>screen.getByRole('region',{name:`${a.label} 주간 거래 내역`});
    const section=screen.getByRole('region',{name:`${a.label} 주간 실거래가`});
    for(const label of ['유효 거래','최저 거래금액','최고 거래금액','거래된 아파트'])expect(within(section).queryByText(label)).toBeNull();
    expect(within(table()).getAllByRole('row')).toHaveLength(8);
    expect(within(table()).getByText('99.00억 원')).toBeTruthy();
    await user.type(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),'85');
    expect(within(table()).getAllByRole('row')).toHaveLength(7);
    expect(within(table()).queryByText('가격단지5')).toBeNull();
    expect(within(table()).getByText('해제최고가')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'이전 주',exact:true}));
    expect(screen.queryByRole('region',{name:`${a.label} 주간 거래 내역`})).toBeNull();
  });
  it('shows cancellation amounts and dates by default and preserves inclusion settings',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}`);
    const loader=()=>Promise.resolve([row(1,{area_m2:60,price_man:60000}),row(2,{cancelled:1,apartment:'해제단지',price_man:900000,raw:{cdealDay:'2026-10-01'}})]);
    const first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    const table=await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(screen.getByRole('checkbox',{name:'해제 거래 포함'}).checked).toBe(true);
    expect(within(table).getAllByRole('row')).toHaveLength(3);
    expect(within(table).getByText('해제일 2026-10-01')).toBeTruthy();
    await user.type(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}),'70');
    expect(within(table).getByText('해제단지')).toBeTruthy();
    expect(within(table).getAllByRole('row')).toHaveLength(2);
    expect(within(table).getByText('90.00억 원')).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'면적 필터 초기화'}));
    await user.click(screen.getByRole('checkbox',{name:'해제 거래 포함'}));
    expect(within(table).queryByText('해제단지')).toBeNull();
    first.unmount();render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(screen.getByRole('checkbox',{name:'해제 거래 포함'}).checked).toBe(false);
  });
  it('combines nonadjacent pyeong bands without filling gaps, respects boundaries and numeric limits, and restores selections',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&dong=${b.region_id}`);
    const pyeongs=[9.9999,10,19.9999,20,29.9999,30,39.9999,40];
    const loader=vi.fn((_,code)=>Promise.resolve([
      ...pyeongs.map((area,index)=>row(index+1,{region_code:code,area_m2:area*PYEONG_M2,apartment:`전용${area}평단지`,price_man:(index+1)*10000})),
      row(99,{region_code:code,area_m2:12*PYEONG_M2,apartment:'해제평대단지',cancelled:1,price_man:990000})
    ]));
    const first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${b.label} 주간 거래 내역`});
    const picker=()=>within(screen.getByRole('group',{name:'전용평대 빠른 선택'}));
    await user.click(picker().getByRole('button',{name:'10평대',exact:true}));
    expect(readPreferences('weekly')).toMatchObject({minArea:10*PYEONG_M2,maxArea:20*PYEONG_M2});
    expect(Number(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}).value)).toBe(Number((10*PYEONG_M2).toFixed(4)));
    expect(Number(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value)).toBe(Number((20*PYEONG_M2).toFixed(4)));
    expect(screen.getByRole('slider',{name:'최소 전용면적 슬라이더 (㎡)'}).value).toBe(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}).value);
    expect(screen.getByRole('slider',{name:'최대 전용면적 슬라이더 (㎡)'}).value).toBe(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value);
    await user.click(picker().getByRole('button',{name:'30평대',exact:true}));
    expect(readPreferences('weekly')).toMatchObject({minArea:10*PYEONG_M2,maxArea:40*PYEONG_M2});
    expect(Number(screen.getByRole('slider',{name:'최대 전용면적 슬라이더 (㎡)'}).value)).toBe(Number((40*PYEONG_M2).toFixed(4)));
    for(const region of [a,b]){
      const table=screen.getByRole('region',{name:`${region.label} 주간 거래 내역`});
      expect(within(table).getAllByRole('row')).toHaveLength(6);
      for(const area of [10,19.9999,30,39.9999])expect(within(table).getByText(`전용${area}평단지`)).toBeTruthy();
      for(const area of [9.9999,20,29.9999,40])expect(within(table).queryByText(`전용${area}평단지`)).toBeNull();
    }
    fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'100'}});
    expect(within(screen.getByRole('region',{name:`${a.label} 주간 거래 내역`})).getAllByRole('row')).toHaveLength(5);
    await user.click(screen.getByRole('button',{name:'평 (전용)',exact:true}));
    expect(readPreferences('weekly')).toMatchObject({areaBands:[10,30],maxArea:100});
    expect(loader).toHaveBeenCalledTimes(2);
    first.unmount();window.history.replaceState(null,'','/');
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${b.label} 주간 거래 내역`});
    expect(picker().getByRole('button',{name:'10평대',exact:true}).getAttribute('aria-pressed')).toBe('true');
    expect(picker().getByRole('button',{name:'20평대',exact:true}).getAttribute('aria-pressed')).toBe('false');
    expect(picker().getByRole('button',{name:'30평대',exact:true}).getAttribute('aria-pressed')).toBe('true');
    const table=()=>screen.getByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(within(table()).getAllByRole('row')).toHaveLength(5);
    await user.click(picker().getByRole('button',{name:'10평대',exact:true}));
    expect(within(table()).getAllByRole('row')).toHaveLength(3);
    expect(screen.getByRole('spinbutton',{name:'최소 전용면적 (평)'}).value).toBe('30');
    expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (평)'}).value).toBe('40');
    await user.click(picker().getByRole('button',{name:'전체 평대',exact:true}));
    expect(readPreferences('weekly')).toMatchObject({areaBands:[],minArea:'',maxArea:''});
    expect(within(table()).getAllByRole('row')).toHaveLength(10);
    await user.click(picker().getByRole('button',{name:'20평대',exact:true}));
    expect(within(table()).getAllByRole('row')).toHaveLength(3);
    expect(screen.getByRole('slider',{name:'최소 전용면적 슬라이더 (평)'}).value).toBe('20');
    expect(screen.getByRole('slider',{name:'최대 전용면적 슬라이더 (평)'}).value).toBe('30');
    await user.click(picker().getByRole('button',{name:'20평대',exact:true}));
    expect(readPreferences('weekly')).toMatchObject({areaBands:[],minArea:'',maxArea:''});
    expect(within(table()).getAllByRole('row')).toHaveLength(10);
    await user.click(picker().getByRole('button',{name:'20평대',exact:true}));
    await user.click(screen.getByRole('button',{name:'면적 필터 초기화'}));
    expect(readPreferences('weekly')).toMatchObject({areaBands:[],minArea:'',maxArea:''});
    expect(within(table()).getAllByRole('row')).toHaveLength(10);
  });
  it('connects both slider handles to the filters, prevents crossing and supports unbounded endpoints',async()=>{
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}`);
    render(<App initialManifest={manifest} districtLoader={()=>Promise.resolve([row(1,{area_m2:60}),row(2),row(3,{area_m2:120})])}/>);
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    const lower=screen.getByRole('slider',{name:'최소 전용면적 슬라이더 (㎡)'});
    const upper=screen.getByRole('slider',{name:'최대 전용면적 슬라이더 (㎡)'});
    fireEvent.change(upper,{target:{value:'85'}});
    fireEvent.change(lower,{target:{value:'60'}});
    expect(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}).value).toBe('60');
    expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value).toBe('85');
    expect(within(screen.getByRole('region',{name:`${a.label} 주간 거래 내역`})).getAllByRole('row')).toHaveLength(3);
    fireEvent.keyDown(lower,{key:'ArrowRight'});
    expect(lower.value).toBe('61');
    fireEvent.change(lower,{target:{value:'100'}});
    expect(lower.value).toBe('85');expect(screen.queryByRole('alert')).toBeNull();
    fireEvent.change(upper,{target:{value:'40'}});
    expect(upper.value).toBe('85');
    fireEvent.change(lower,{target:{value:'0'}});
    fireEvent.change(upper,{target:{value:upper.max}});
    expect(readPreferences('weekly')).toMatchObject({minArea:'',maxArea:''});
    fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'400'}});
    expect(Number(upper.max)).toBeGreaterThanOrEqual(400);expect(upper.value).toBe('400');
  });
  it('filters every dong inclusively, keeps exact bounds across units and revisits, and resets the range',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&dong=${b.region_id}`);
    const loader=vi.fn((_,code)=>Promise.resolve([
      row(1,{region_code:code,area_m2:59.99,apartment:'작은단지',price_man:30000}),
      row(2,{region_code:code,area_m2:60,apartment:'경계60단지',price_man:60000}),
      row(3,{region_code:code,area_m2:85,apartment:'경계85단지',price_man:100000}),
      row(4,{region_code:code,area_m2:85.01,apartment:'큰단지',price_man:150000}),
      row(5,{region_code:code,cancelled:1,area_m2:70,apartment:'해제단지',price_man:900000})
    ]));
    const first=render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${b.label} 주간 거래 내역`});
    await user.click(screen.getByRole('checkbox',{name:'해제 거래 포함'}));
    await user.type(screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'}),'60');
    await user.type(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),'85');
    for(const region of [a,b]){
      const table=screen.getByRole('region',{name:`${region.label} 주간 거래 내역`});
      expect(within(table).getAllByRole('row')).toHaveLength(3);
      expect(within(table).queryByText('작은단지')).toBeNull();
      expect(within(table).queryByText('큰단지')).toBeNull();
      expect(within(table).queryByText('해제단지')).toBeNull();
    }
    await user.click(screen.getByRole('button',{name:'평 (전용)',exact:true}));
    expect(screen.getByRole('spinbutton',{name:'최소 전용면적 (평)'}).value).toBe('18.15');
    expect(readPreferences('weekly')).toMatchObject({minArea:60,maxArea:85});
    expect(within(screen.getByRole('region',{name:`${a.label} 주간 거래 내역`})).getAllByRole('row')).toHaveLength(3);
    expect(loader).toHaveBeenCalledTimes(2);
    first.unmount();window.history.replaceState(null,'','/');
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('region',{name:`${b.label} 주간 거래 내역`});
    expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (평)'}).value).toBe('25.7125');
    await user.click(screen.getByRole('button',{name:'㎡',exact:true}));
    const min=screen.getByRole('spinbutton',{name:'최소 전용면적 (㎡)'});
    expect(min.value).toBe('60');
    await user.clear(min);await user.type(min,'90');
    expect(screen.getByRole('alert').textContent).toContain('최소 전용면적은 최대 전용면적보다');
    expect(screen.getAllByText('이 주의 면적 조건에 맞는 유효 거래가 없습니다.')).toHaveLength(2);
    await user.click(screen.getByRole('button',{name:'면적 필터 초기화'}));
    expect(min.value).toBe('');expect(screen.queryByRole('alert')).toBeNull();
    expect(within(screen.getByRole('region',{name:`${a.label} 주간 거래 내역`})).getAllByRole('row')).toHaveLength(5);
  });
  it('stacks multiple districts in selection order, keeps selections during search, caches shared districts and changes area units',async()=>{
    const user=userEvent.setup();
    const data=[row(1),row(2,{deal_month:'202610',deal_date:'2026-10-04',price_man:120000}),row(3,{deal_date:'2026-09-27',price_man:700000}),row(4,{cancelled:1,price_man:800000}),row(5,{dong:'동천동',apartment:'동천단지'}),row(6,{deal_date:'2026-10-05',price_man:900000})];
    const loader=vi.fn((_,code)=>Promise.resolve(code==='41465'?data:[row(1,{region_code:'11110',apartment:'서울단지',price_man:50000})]));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByText('실거래가를 볼 동을 선택해 주세요.');
    await user.click(screen.getByRole('checkbox',{name:'해제 거래 포함'}));
    expect(loader).not.toHaveBeenCalled();
    await user.click(screen.getByRole('checkbox',{name:/풍덕천동.*용인시/}));
    const sectionA=screen.getByRole('region',{name:`${a.label} 주간 실거래가`});
    await within(sectionA).findByText('12.00억 원');
    const tableA=within(sectionA).getByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(within(tableA).getAllByRole('row')).toHaveLength(3);
    await user.click(screen.getByRole('checkbox',{name:/풍덕천동.*종로구/}));
    const sectionB=screen.getByRole('region',{name:`${b.label} 주간 실거래가`});
    await within(sectionB).findByRole('region',{name:`${b.label} 주간 거래 내역`});
    expect(within(sectionA).queryByText('서울단지')).toBeNull();
    await user.click(screen.getByRole('checkbox',{name:/동천동.*용인시/}));
    await screen.findByRole('region',{name:`${c.label} 주간 거래 내역`});
    const stack=document.querySelector('.weekly-stack');
    expect([...stack.children].map(el=>el.getAttribute('aria-label'))).toEqual([a,b,c].map(region=>`${region.label} 주간 실거래가`));
    expect(loader).toHaveBeenCalledTimes(2);
    await user.type(screen.getByRole('searchbox',{name:'주간 동 검색'}),'동천');
    expect(screen.queryByRole('checkbox',{name:/풍덕천동.*용인시/})).toBeNull();
    expect(screen.getByRole('region',{name:`${a.label} 주간 실거래가`})).toBeTruthy();
    await user.click(screen.getByRole('button',{name:'평 (전용)',exact:true}));
    expect(within(tableA).getAllByRole('cell',{name:'25.7평'})).toHaveLength(2);
    await user.click(screen.getByRole('button',{name:`${b.label} 선택 해제`}));
    expect(screen.queryByRole('region',{name:`${b.label} 주간 실거래가`})).toBeNull();
    expect(window.location.search).toContain('week=2026-09-28');
    expect(new URLSearchParams(window.location.search).getAll('dong')).toEqual([a.region_id,c.region_id]);
  });
  it('restores selected dongs from the URL, paginates each card and resets pages on week changes',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&dong=invalid&dong=${a.region_id}&week=2026-10-01`);
    const loader=vi.fn(()=>Promise.resolve(Array.from({length:52},(_,i)=>row(i+1,{price_man:i===0?77000:100000}))));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    const table=await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(within(table).getAllByRole('row')).toHaveLength(51);
    await user.click(screen.getByRole('button',{name:`${a.label} 다음 거래 페이지`}));
    expect(within(table).getAllByRole('row')).toHaveLength(3);
    expect(within(table).getByText('7.70억 원')).toBeTruthy();
    await user.type(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),'85');
    await waitFor(()=>expect(screen.getByRole('button',{name:`${a.label} 이전 거래 페이지`}).disabled).toBe(true));
    expect(within(screen.getByRole('region',{name:`${a.label} 주간 거래 내역`})).getAllByRole('row')).toHaveLength(51);
    await user.click(screen.getByRole('button',{name:'면적 필터 초기화'}));
    await user.click(screen.getByRole('button',{name:'이전 주',exact:true}));
    await screen.findByText('이 주에 조회되는 거래가 없습니다.');
    await user.click(screen.getByRole('button',{name:'다음 주',exact:true}));
    const refreshed=screen.getByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(within(refreshed).getAllByRole('row')).toHaveLength(51);
    expect(screen.getByRole('button',{name:`${a.label} 이전 거래 페이지`}).disabled).toBe(true);
    expect(screen.getByRole('button',{name:'다음 주',exact:true}).disabled).toBe(true);
    expect(loader).toHaveBeenCalledTimes(1);
    await user.click(screen.getByRole('button',{name:'데이터 안내',exact:true}));
    await user.click(screen.getByRole('button',{name:'동 별 실거래가',exact:true}));
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(screen.getByRole('checkbox',{name:/풍덕천동.*용인시/}).checked).toBe(true);
  });
  it('isolates a failed district, retries it, and never fetches an uncollected district',async()=>{
    const user=userEvent.setup();
    window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&dong=${b.region_id}&dong=${uncollected.region_id}`);
    let attempts=0;
    const loader=vi.fn((_,code)=>code==='11110'&&attempts++===0?Promise.reject(new Error('failure')):Promise.resolve([row(1,{region_code:code})]));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('alert');
    await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
    expect(screen.getByText('아직 수집된 자료가 없는 동입니다.')).toBeTruthy();
    expect(loader.mock.calls.map(call=>call[1]).sort()).toEqual(['11110','41465']);
    await user.click(screen.getByRole('button',{name:'다시 불러오기',exact:true}));
    await screen.findByRole('region',{name:`${b.label} 주간 거래 내역`});
    expect(loader).toHaveBeenCalledTimes(3);
    await user.click(screen.getByRole('button',{name:'선택 모두 해제'}));
    expect(screen.queryByRole('region',{name:`${a.label} 주간 실거래가`})).toBeNull();
    expect(screen.getByText('실거래가를 볼 동을 선택해 주세요.')).toBeTruthy();
  });
  it('does not restore a removed card when an earlier request finishes late',async()=>{
    const user=userEvent.setup();let resolve;
    const loader=vi.fn(()=>new Promise(done=>{resolve=done;}));
    render(<App initialManifest={manifest} districtLoader={loader}/>);
    await screen.findByRole('checkbox',{name:/풍덕천동.*용인시/});
    await user.click(screen.getByRole('checkbox',{name:/풍덕천동.*용인시/}));
    await waitFor(()=>expect(loader).toHaveBeenCalledTimes(1));
    await user.click(screen.getByRole('button',{name:`${a.label} 선택 해제`}));
    resolve([row(1)]);
    await waitFor(()=>expect(screen.queryByRole('region',{name:`${a.label} 주간 실거래가`})).toBeNull());
  });
});

it('collapses each numbered filter group independently without clearing inputs, cancellation settings or results',async()=>{
  const user=userEvent.setup();
  window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}`);
  const loader=vi.fn(()=>Promise.resolve([row(1),row(2,{cancelled:1,raw:{cdealDay:'2026-10-01'}})]));
  render(<App initialManifest={manifest} districtLoader={loader}/>);
  const table=await screen.findByRole('region',{name:`${a.label} 주간 거래 내역`});
  expect(screen.getByRole('button',{name:'동 별 실거래가',exact:true})).toBeTruthy();
  expect([...document.querySelectorAll('.weekly-controls .filter-step')].map(step=>step.textContent)).toEqual(['01','02','03','04']);
  const options=screen.getByRole('region',{name:'기타 옵션'});
  expect(within(options).getByRole('checkbox',{name:'해제 거래 포함'}).checked).toBe(true);
  const date=screen.getByLabelText('조회 주 기준 날짜').value;
  fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'85'}});
  for(const title of ['조회 기간','전용면적','조회할 동']){
    const button=screen.getByRole('button',{name:title+' 접기'});
    await user.click(button);
    expect(button.getAttribute('aria-expanded')).toBe('false');
    expect(document.getElementById(button.getAttribute('aria-controls')).hidden).toBe(true);
  }
  expect(screen.getByLabelText('조회 주 기준 날짜').closest('[hidden]')).toBeTruthy();
  expect(screen.queryByRole('spinbutton',{name:'최대 전용면적 (㎡)'})).toBeNull();
  expect(within(table).getAllByRole('row')).toHaveLength(3);
  await user.click(within(options).getByRole('checkbox',{name:'해제 거래 포함'}));
  expect(within(table).getAllByRole('row')).toHaveLength(2);
  await user.click(screen.getByRole('button',{name:'기타 옵션 접기'}));
  expect(screen.queryByRole('checkbox',{name:'해제 거래 포함'})).toBeNull();
  const reopen=screen.getByRole('button',{name:'기타 옵션 펼치기'});reopen.focus();await user.keyboard('{Enter}');
  expect(within(options).getByRole('checkbox',{name:'해제 거래 포함'}).checked).toBe(false);
  for(const title of ['조회 기간','전용면적','조회할 동'])await user.click(screen.getByRole('button',{name:title+' 펼치기'}));
  expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value).toBe('85');
  expect(screen.getByLabelText('조회 주 기준 날짜').value).toBe(date);
  expect(screen.getByRole('checkbox',{name:/풍덕천동.*용인시/}).checked).toBe(true);
  expect(readPreferences('weekly').includeCancelled).toBe(false);
  expect(loader).toHaveBeenCalledTimes(1);
});


it('selects personal favorite dongs independently of search, synchronizes both pickers and persists selections without changing favorites',async()=>{
 const user=userEvent.setup();savePreferences('viewer',{regions:[b.region_id,a.region_id,uncollected.region_id,'dong_99999999']});
 const loader=vi.fn(async(_,code)=>[row(1,{region_code:code})]);
 let view=render(<App initialManifest={manifest} districtLoader={loader}/>);
 const favorites=await screen.findByRole('group',{name:'즐겨찾기한 동 선택'});
 expect(within(favorites).getAllByRole('checkbox').map(input=>input.closest('label').textContent)).toEqual([b,a,uncollected].map(region=>region.dongs[0]+region.region_name+(manifest.districts[region.region_code]?'':' · 미수집')));
 expect(within(favorites).getAllByRole('checkbox').every(input=>!input.checked)).toBe(true);expect(loader).not.toHaveBeenCalled();
 await user.type(screen.getByRole('searchbox',{name:'주간 동 검색'}),'동천');
 const search=screen.getByRole('group',{name:'주간 조회할 동 선택'});expect(within(search).queryByRole('checkbox',{name:/풍덕천동/})).toBeNull();
 await user.click(within(favorites).getByRole('checkbox',{name:/풍덕천동.*종로구/}));
 await user.click(within(favorites).getByRole('checkbox',{name:/풍덕천동.*용인시/}));
 await screen.findByRole('region',{name:a.label+' 주간 거래 내역'});
 expect(new URLSearchParams(location.search).getAll('dong')).toEqual([b.region_id,a.region_id]);
 await user.clear(screen.getByRole('searchbox',{name:'주간 동 검색'}));
 expect(within(search).getByRole('checkbox',{name:/풍덕천동.*용인시/}).checked).toBe(true);
 await user.click(within(search).getByRole('checkbox',{name:/풍덕천동.*용인시/}));
 expect(within(favorites).getByRole('checkbox',{name:/풍덕천동.*용인시/}).checked).toBe(false);
 await user.click(within(favorites).getByRole('checkbox',{name:/매탄동/}));
 expect(screen.getByText('아직 수집된 자료가 없는 동입니다.')).toBeTruthy();expect(loader.mock.calls.map(call=>call[1]).sort()).toEqual(['11110','41465']);
 expect(readPreferences('viewer').regions).toEqual([b.region_id,a.region_id,uncollected.region_id,'dong_99999999']);
 view.unmount();window.history.replaceState(null,'','/');view=render(<App initialManifest={manifest} districtLoader={loader}/>);
 const restored=await screen.findByRole('group',{name:'즐겨찾기한 동 선택'});
 expect(within(restored).getByRole('checkbox',{name:/풍덕천동.*종로구/}).checked).toBe(true);expect(within(restored).getByRole('checkbox',{name:/매탄동/}).checked).toBe(true);
 await user.click(screen.getByRole('button',{name:'선택 모두 해제'}));
 expect(within(restored).getAllByRole('checkbox').every(input=>!input.checked)).toBe(true);expect(readPreferences('explorer').weeklyIds).toEqual([]);
 expect(readPreferences('viewer').regions).toEqual([b.region_id,a.region_id,uncollected.region_id,'dong_99999999']);
});

it('shows how to add personal favorite dongs when none are saved, without importing administrator collection favorites',async()=>{
 render(<App initialManifest={manifest}/>);
 const favorites=await screen.findByRole('region',{name:'즐겨찾기한 동'});
 expect(within(favorites).getByText('지역 지도에서 별표로 동을 즐겨찾기하면 여기에 표시됩니다.')).toBeTruthy();
 expect(within(favorites).queryByRole('checkbox')).toBeNull();
 expect(screen.getByRole('group',{name:'주간 조회할 동 선택'})).toBeTruthy();
});

it('collapses whole filters and individual dong panels independently while preserving pages and nested filter state',async()=>{
 const user=userEvent.setup();window.history.replaceState(null,'',`/?tab=weekly&dong=${a.region_id}&dong=${b.region_id}`);
 const loader=vi.fn(async(_,code)=>Array.from({length:52},(_,index)=>row(index+1,{region_code:code})));
 render(<App initialManifest={manifest} districtLoader={loader}/>);
 const panelA=await screen.findByRole('region',{name:a.label+' 주간 실거래가'});
 const tableA=await within(panelA).findByRole('region',{name:a.label+' 주간 거래 내역'});
 const tableB=await screen.findByRole('region',{name:b.label+' 주간 거래 내역'});
 fireEvent.change(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}),{target:{value:'90'}});
 await user.click(screen.getByRole('checkbox',{name:'해제 거래 포함'}));
 await user.click(screen.getByRole('button',{name:'전용면적 접기'}));
 await user.click(screen.getByRole('button',{name:a.label+' 다음 거래 페이지'}));
 expect(within(tableA).getAllByRole('row')).toHaveLength(3);
 const url=location.search,settings=readPreferences('weekly');
 const collapse=within(panelA).getByRole('button',{name:a.label+' 실거래가 접기'});await user.click(collapse);
 expect(collapse.getAttribute('aria-expanded')).toBe('false');
 expect(document.getElementById(collapse.getAttribute('aria-controls')).contains(tableA)).toBe(true);
 expect(screen.queryByRole('region',{name:a.label+' 주간 거래 내역'})).toBeNull();
 expect(within(tableB).getAllByRole('row')).toHaveLength(51);
 await user.click(screen.getByRole('button',{name:'조회 필터 접기'}));
 expect(screen.queryByRole('button',{name:'조회 기간 접기'})).toBeNull();
 collapse.focus();await user.keyboard('{Enter}');
 expect(within(tableA).getAllByRole('row')).toHaveLength(3);
 expect(location.search).toBe(url);expect(readPreferences('weekly')).toEqual(settings);
 await user.click(screen.getByRole('button',{name:'조회 필터 펼치기'}));
 expect(screen.queryByRole('spinbutton',{name:'최대 전용면적 (㎡)'})).toBeNull();
 await user.click(screen.getByRole('button',{name:'전용면적 펼치기'}));
 expect(screen.getByRole('spinbutton',{name:'최대 전용면적 (㎡)'}).value).toBe('90');
 expect(screen.getByRole('checkbox',{name:'해제 거래 포함'}).checked).toBe(false);
 expect(loader).toHaveBeenCalledTimes(2);
});
