import React from 'react';
import {Database,Play,Square,RefreshCw} from 'lucide-react';
import {formatNumber} from '../src/domain.mjs';
export default function ApartmentMasterPanel({state,pending,running,action}){
 const stats=state.stats.apartmentMaster||{},byRegion=new Map((stats.regions||[]).map(r=>[r.region_id,r])),selected=state.catalog.filter(r=>state.saved.includes(r.region_id)),ready=state.buildingRegistryKeyReady&&state.vworldKeyReady&&state.coordinateKeyReady;
 return <section id="apartment-master" className="panel"><div className="panel-heading"><Database size={19}/><h2>지역 전체 아파트 정보 DB</h2><span className="badge">{stats.complete?'필수 정보 확인 완료':'수집·확인 필요'}</span></div>
 <p>저장한 수집 지역의 건축물대장 전체 목록을 조회합니다. 거래가 없는 아파트도 포함하며, 단지·건물 동·대표/부속 필지·출입구와 건물 외곽선·용도지역을 구분해 저장합니다.</p>
 <div className="coordinate-counts"><span>단지 <strong>{formatNumber(stats.complexes||0)}개</strong></span><span>건물 동 <strong>{formatNumber(stats.buildings||0)}개</strong></span><span>위치 <strong>{formatNumber(stats.withLocation||0)}개</strong></span><span>전체 필지 경계 <strong>{formatNumber(stats.withBoundary||0)}개</strong></span><span>건축년도 <strong>{formatNumber(stats.withYear||0)}개</strong></span><span>건물 외곽선 <strong>{formatNumber(stats.withFootprints||0)}개</strong></span><span>개별공시지가 <strong>{formatNumber(stats.withLandPrice||0)}개</strong></span><span>용도지역 <strong>{formatNumber(stats.withZoning||0)}개</strong></span><span>법정동 경계 <strong>{formatNumber(stats.withRegionBoundary||0)}/{formatNumber(stats.regions?.length||0)}</strong></span><span>시·군·구 경계 <strong>{formatNumber(stats.withDistrictBoundary||0)}개</strong></span></div>
 {!ready&&<div className="notice error">공식 자료 수집 설정이 필요합니다. .env에 BUILDING_REGISTER_SERVICE_KEY(건축HUB 건축물대장 활용 승인), VWORLD_API_KEY(데이터 API), JUSO_COORDINATE_SEARCH_KEY를 등록하세요. 브이월드 등록 URL이 다르면 VWORLD_DOMAIN도 설정하세요.</div>}
 <div className="action-row"><button className="primary" disabled={pending||running||!ready||!state.saved.length} onClick={()=>action('apartment-master',{})}><Play size={16}/>전체 아파트 수집·DB 구성</button><button disabled={pending||running||!ready||!state.saved.length} onClick={()=>action('apartment-master',{refresh:true})}><RefreshCw size={16}/>위치·필지 경계도 다시 조회</button><button disabled={pending} onClick={()=>action('reload',{},()=>{})}>아파트 수집 설정 확인</button>{running&&state.job.kind==='apartment-master'&&!state.job.external&&<button disabled={pending} onClick={()=>action('cancel',{})}><Square size={16}/>수집 중단</button>}</div>
 {state.job.kind==='apartment-master'&&<div className="job-status" role="status"><strong>{state.job.message}</strong><progress max={state.job.total||1} value={state.job.completed}/><small>{state.job.completed}/{state.job.total} · {state.job.status}</small></div>}
 <p className="small-note">경계는 건축물대장에 연결된 대표·부속 필지의 공식 지적 도형입니다. 담장 위치와 다를 수 있습니다. 빈 필드·미분류 용도·실패 지역을 남겨 두며, 필수 정보가 모두 확인되기 전에는 전체 구축 완료로 표시하지 않습니다.</p>
 <div className="admin-table-scroll"><table><thead><tr><th>선택 지역</th><th>상태</th><th>전체 대장 건물</th><th>아파트 단지</th><th>최근 확인</th></tr></thead><tbody>{selected.map(s=>{const r=byRegion.get(s.region_id);return <tr key={s.region_id}><td>{s.label}</td><td>{({pending:'대기',running:'조회 중',scanned:'전체 페이지 확인',error:'실패'})[r?.status]||'미수집'}{r?.error&&<small>{r.error}</small>}</td><td>{r?formatNumber(r.source_counts?.getBrTitleInfo||0):'—'}</td><td>{r?formatNumber(r.complexes||0):'—'}</td><td>{r?.fetched_at?new Date(r.fetched_at).toLocaleString('ko-KR'):'—'}</td></tr>;})}</tbody></table></div>
 {!!stats.issues&&<details><summary>미확인 항목 {formatNumber(stats.issues)}건</summary><div className="admin-table-scroll"><table><thead><tr><th>지역</th><th>식별자</th><th>사유</th></tr></thead><tbody>{(stats.issueList||[]).slice(0,100).map(p=><tr key={p.issue_key}><td>{state.catalog.find(r=>r.region_id===p.region_id)?.label||p.region_id}</td><td>{p.apartment_id||p.building_id}</td><td>{p.detail}</td></tr>)}</tbody></table></div>{stats.issues>100&&<p className="small-note">화면에는 앞 100건을 표시합니다. 전체 이슈는 DB의 apartment_master_issues에 보존됩니다.</p>}</details>}
 </section>;
}
